### ISSUE TITLE
How to access?

### ISSUE THREAD

**Issue by yamatt** [rbrower3/openshift-elasticsearch-cartridge#11]
Hi There, thanks so much for this project by the way.

I'm struggling to find how I'm supposed to access my ES instance, from Python, let's say. I'd need to access it from another `openshift` app. Or do I?

**Comment by arrakisdunes** [comment]
Hi,

I have the same "problem" as yamatt, but in my case I wanna connect with tomcat (my webapp is in j2ee). I cannot figure it out how to connect.

Thanks

**Comment by rbrower3** [comment]
Hi @yamatt, sorry for the delay in responding. No, you don't necessarily need to access ES from another openshift app. You should be able to access it anywhere. From python something like this should work:

```python
from datetime import datetime
from elastic search import Elasticsearch

es = Elasticsearch([{'host':"your-es-instance-name.rhcloud.com", 'port':80}])
# index a document
es.index(index="my-index", doc_type="test-type", id=42, body={"any": "data", "timestamp": datetime.now()})
# get the document
es.get(index="my-index", doc_type="test-type", id=42)
# returns:
# {u'_type': u'test-type', u'_source': {u'timestamp': u'2015-05-30T19:04:43.418911', u'any': u'data'}, u'_index': u'my-index', u'_version': 1, u'found': True, u'_id': u'42'}
```


Hi @arrakisdunes, I've not tried to connect from tomcat but I think you'll need to do something like they show here: https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/client.html 
I guess you can specify the hostname/port in some tomcat config file, but, again I haven't tried it so I'm afraid I don't know what it is.

**Comment by arrakisdunes** [comment]
I did check the link (thanks for that) and also I search about this subject. What I found is the port 80 is REST and is hard to use this. Better is to use the transport client (usualy 9300). How can I enable this port?

**Comment by yamatt** [comment]
@arrakisdunes That is exactly what my problem was (I did work it out in the end) that the ES port in OpenShift is 80 and not the default.

**Comment by gkfirst8** [comment]
Do you mean to say that one should not use the transport client? Or should the port 80 be used as the transport client port?

**Comment by yamatt** [comment]
The REST port here is port 80. I've not used the transport client.
